<a href="https://colab.research.google.com/github/Arpit0134/Python-for-Oil-Gas/blob/main/Lac7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Functions**


In [ ]:
def api(sg):
  api = 141.5/sg - 131.5
  print(f'The api gravity is {api}')

In [ ]:
api(0.8)

The api gravity is 45.375


In [ ]:
def darcy_coefficient(C=141.2):
  q = float(input('Enter flowrate in STB/D: '))
  mu = float(input('Enter viscosity in cP: '))
  B = float(input('Enter FVF in rb/STB: '))
  k = float(input('Enter Perm in mD: '))
  h = float(input('Enter Thickness in ft: '))

  coeff = C*q*mu*B/(k*h)
  return coeff

In [ ]:
darcy_coefficient()

Enter flowrate in STB/D: 100
Enter viscosity in cP: 1
Enter FVF in rb/STB: 2
Enter Perm in mD: 10
Enter Thickness in ft: 300


9.413333333333332

**Numpy**

In [2]:
import numpy as np

In [ ]:
np.array(35464)

array(35464)

In [ ]:
porosity = [0.2,0.4,0.8,0.5]

In [ ]:
porosity

[0.2, 0.4, 0.8, 0.5]

In [ ]:
type(porosity)

list

In [ ]:
arr_porosity = np.array(porosity)

In [ ]:
arr_porosity

array([0.2, 0.4, 0.8, 0.5])

In [ ]:
type(arr_porosity)

numpy.ndarray

In [ ]:
tup_por = tuple(porosity)

In [ ]:
tup_por

(0.2, 0.4, 0.8, 0.5)

In [ ]:
np.array(tup_por)

array([0.2, 0.4, 0.8, 0.5])

#Dimension

0d: array having one element

In [3]:
arr = np.array(45)

In [4]:
arr

array(45)

In [5]:
arr.ndim

0

In [6]:
arr = np.array(45,35)

TypeError: ignored

**1D array**

In [8]:
arr_1d = np.array([1,2,3,4,5,6,7,8])

In [9]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr_1d.ndim

1

**2d array**

In [13]:
perm = np.array([[1,2,3],[5,8,9],[7,5,3]])

In [14]:
perm

array([[1, 2, 3],
       [5, 8, 9],
       [7, 5, 3]])

In [15]:
perm.ndim

2

In [17]:
arr_2d = np.array([[1,2,3],[4,6,5],[7,9,5,6]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [18]:
arr_2d.ndim

1

In [19]:
arr_2d

array([list([1, 2, 3]), list([4, 6, 5]), list([7, 9, 5, 6])], dtype=object)

In [20]:
arr_2d[1]

[4, 6, 5]

In [21]:
a = np.array([2,3.7,'arpit'])

In [22]:
a

array(['2', '3.7', 'arpit'], dtype='<U32')

**3d arrays**

In [23]:
arr_3d = np.array([[[1,2,3],[3,4,5]],[[4,5,6],[6,7,8]]])

In [24]:
arr_3d

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [25]:
arr_3d.ndim

3

In [27]:
arr_3d[0]

array([[1, 2, 3],
       [3, 4, 5]])

In [28]:
arr_3d[0][1]

array([3, 4, 5])

In [29]:
arr_3d[0][1][2]

5

In [30]:
arr_3d[0,1,2]

5

In [31]:
arr_4d = np.array([[[[1,2,3,4],[3,4,5,6],[6,7,8,9]],[[34,56,78,45],[98,54,32,12],[956,67,23,67]]],[[[11,22,343,42],[33,44,55,665],[656,73,8,9]],[[34,5326,78,4325],[98,5324,3232,12],[56,67,23,67]]]])

In [32]:
arr_4d

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   6,    7,    8,    9]],

        [[  34,   56,   78,   45],
         [  98,   54,   32,   12],
         [ 956,   67,   23,   67]]],


       [[[  11,   22,  343,   42],
         [  33,   44,   55,  665],
         [ 656,   73,    8,    9]],

        [[  34, 5326,   78, 4325],
         [  98, 5324, 3232,   12],
         [  56,   67,   23,   67]]]])

In [37]:
arr_4d[1,0,1,2]  #going Higher dimesnion to lower dimension

55

In [39]:
arr = np.array([3,4,5],ndmin = 5)

In [40]:
arr

array([[[[[3, 4, 5]]]]])

In [42]:
arr.ndim

5

**Shape:Checking Shape of Arrays**

In [43]:
arr = np.array([1,2,3])

In [44]:
arr

array([1, 2, 3])

In [45]:
arr.shape

(3,)

In [49]:
arr_2d = np.array([[1,2,3],[5,8,9],[7,5,3],[3,5,3]])

In [50]:
arr_2d

array([[1, 2, 3],
       [5, 8, 9],
       [7, 5, 3],
       [3, 5, 3]])

In [51]:
arr_2d.shape

(4, 3)

In [54]:
 arr_3d = np.array([[[1,2,3,4],[3,4,5,6],[6,7,8,9]],[[4,5,6,0],[6,7,8,1],[7,6,4,6]]])

In [55]:
arr_3d

array([[[1, 2, 3, 4],
        [3, 4, 5, 6],
        [6, 7, 8, 9]],

       [[4, 5, 6, 0],
        [6, 7, 8, 1],
        [7, 6, 4, 6]]])

In [56]:
arr_3d.shape

(2, 3, 4)

In [57]:
 arr_4d = np.array([[[[1,2,3,4],[3,4,5,6],[6,7,8,9]],[[34,56,78,45],[98,54,32,12],[956,67,23,67]]],[[[11,22,343,42],[33,44,55,665],[656,73,8,9]],[[34,5326,78,4325],[98,5324,3232,12],[56,67,23,67]]]])

In [58]:
arr_4d

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   6,    7,    8,    9]],

        [[  34,   56,   78,   45],
         [  98,   54,   32,   12],
         [ 956,   67,   23,   67]]],


       [[[  11,   22,  343,   42],
         [  33,   44,   55,  665],
         [ 656,   73,    8,    9]],

        [[  34, 5326,   78, 4325],
         [  98, 5324, 3232,   12],
         [  56,   67,   23,   67]]]])

In [59]:
arr_4d.shape

(2, 2, 3, 4)

In [60]:
arr = np.array([3,4,5],ndmin = 5)

In [61]:
arr

array([[[[[3, 4, 5]]]]])

In [62]:
arr.shape

(1, 1, 1, 1, 3)

**Generating Arrays**

arange

-np.arange(start,stop,step)

In [64]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [65]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [66]:
np.arange(0,5500,500)

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

In [67]:
np.arange(0,5001,500)

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

**Linspace:create linerly spaced arrays**

np.linspace(start,stop,number of points)

stop point is also included

In [69]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Zeroes,Ones and Indentity matrices

np.zeros((shape of array))

In [71]:
a = np.zeros((5,4))

In [72]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
a[2,2] = 4

In [74]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
b = np.ones((8,6))

In [78]:
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [79]:
c = np.ones((2,3,4))

In [80]:
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [81]:
b*5

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

Identity matrices = diagonal

In [82]:
i = np.eye(6)

In [83]:
i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [84]:
i*64 + 36

array([[100.,  36.,  36.,  36.,  36.,  36.],
       [ 36., 100.,  36.,  36.,  36.,  36.],
       [ 36.,  36., 100.,  36.,  36.,  36.],
       [ 36.,  36.,  36., 100.,  36.,  36.],
       [ 36.,  36.,  36.,  36., 100.,  36.],
       [ 36.,  36.,  36.,  36.,  36., 100.]])

In [85]:
x = np.eye(3,4)

In [86]:
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])